### ISSUE TITLE
V-for remove the first line

### ISSUE THREAD

**Issue by danielgara** [PacktPublishing/-Vue.js-3-By-Example#1]
Dear author, remember to remove the first line of that file.

https://github.com/PacktPublishing/-Vue.js-3-By-Example/blob/d1c8ee1f91f86ea16047885822451d77ab02f3fa/Chapter01/v-for/index.html#L1

Thanks!

**Comment by deepesh-packt** [comment]
Hey @danielgara 
Thanks for highlighting this. I've removed that line from the file.
