### ISSUE TITLE
chpter 5 ionic auto-hide causes error

### ISSUE THREAD

**Issue by clockwiser** [PacktPublishing/-Vue.js-3-By-Example#11]
In the example, following part of App.vue causes error.

source:
<ion-menu-toggle
              auto-hide="false"    
              v-for="(p, i) in appPages"
              :key="i"

error:
Type 'string' is not assignable to type 'boolean | undefined'.

It seems auto-hide has some problem of type mismatch, but not clear how to solve it.

**Comment by jauyeunggithub** [comment]
It should be `:auto-hide` instead of `auto-hide`

**Comment by clockwiser** [comment]
> It should be `:auto-hide` instead of `auto-hide`
It worked. Thank you.
