### ISSUE TITLE
Chapter 5 example URL requires access key

### ISSUE THREAD

**Issue by clockwiser** [PacktPublishing/-Vue.js-3-By-Example#12]
In CurrencyConverter.vue, retrieve currency rate from the following URL, but the site requires access key.

https://api.exchangeratesapi.io/latest

{
  "success": false,
  "error": {
    "code": 101,
    "type": "missing_access_key",
    "info": "You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]"
  }
}

**Comment by marabesi** [comment]
you can access this link https://apilayer.com/marketplace/exchangerates_data-api#pricing and select free plan to generate a key

**Comment by clockwiser** [comment]
The free plan only provides an apikey. Don't know whether "apikey" and "access_key" are the same thing.
When try the following URL, the site returns error.
https://api.exchangeratesapi.io/latest?access_key=DRPO0QgXbXbWps6RR4bzINSNvTp9xMlB

{
  "success": false,
  "error": {
    "code": 101,
    "type": "invalid_access_key",
    "info": "You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]"
  }
}

**Comment by marabesi** [comment]
according to their docs you need to pass the key via header, as described here https://apilayer.com/docs/article/getting-started.

You can also have a look in this pic that has a snippet:

![image](https://user-images.githubusercontent.com/2129872/234252031-f3b60650-5b82-426d-b58a-90b3c2e60f6b.png)


In other words you cannot access the content via browser as you are doing, I would recommend using postman  for that.

**Comment by clockwiser** [comment]
> according to their docs you need to pass the key via header, as described here https://apilayer.com/docs/article/getting-started.
> 
> You can also have a look in this pic that has a snippet:
> 
> In other words you cannot access the content via browser as you are doing, I would recommend using postman for that.

I tried putting the apikey into headers. It worked with thunder, a vs code plugin, similar to postman. But when use it inside ionic, like in example 5, there was a network error. I am not sure if it is a CORS problem.

**Comment by marabesi** [comment]
Can you post the error here? A screenshot would be even better

**Comment by clockwiser** [comment]
Error is as below. Today it worked at first, then started throwing error again. Could be a timeout problem?

GET https://api.exchangeratesapi.io/latest?base=USD net::ERR_FAILED
caught (in promise) AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

![image](https://user-images.githubusercontent.com/4537946/235012676-ee1a1b58-5eb5-45d9-89dc-7ea0004c50cf.png)

**Comment by marabesi** [comment]
What does it say in the network tab? Is there an HTTP status there?

**Comment by clockwiser** [comment]
Finally it worked. Should change URL.
https://api.apilayer.com/exchangerates_data/latest
