### ISSUE TITLE
Chapter 3 object Module

### ISSUE THREAD

**Issue by quicktwit** [PacktPublishing/-Vue.js-3-By-Example#2]
Hi
When I test the code in "Chapter 3 - Puzzle game" then all the images source are coming as object Module. For example: `<img src="[object Module]" data-v-4a1f852f="">` 
There are no images showing.
How do I solve this?
Thank you

**Comment by jauyeunggithub** [comment]
Did you write the code from scratch by following the book or download the code directly?

**Comment by quicktwit** [comment]
I wrote the code from scratch by following the book. Did I miss something?

**Comment by jauyeunggithub** [comment]
You need to download the images and put them in the same folder as in the sample code.

**Comment by quicktwit** [comment]
Yes, I kept it in the same folder as described in the book. 
<img width="798" alt="Screen Shot 2021-06-01 at 10 15 06" src="https://user-images.githubusercontent.com/4423688/120253465-5f1b4a00-c2c2-11eb-8005-233cd182e814.png">

**Comment by jauyeunggithub** [comment]
If you create your project with Vue CLI, it should be able to load the images with the code in the book.

**Comment by quicktwit** [comment]
When I clone your repo, then it worked. I think I missed something. I will close the issue.
