### ISSUE TITLE
counter is not visible but supposed to be visible

### ISSUE THREAD

**Issue by danushk** [PacktPublishing/-Vue.js-3-By-Example#3]
Hi Vuers -  This is a beginner question so please be kind to me. 

i just started learning vue using this book and i get this for the following code.

for this code - https://github.com/PacktPublishing/-Vue.js-3-By-Example/tree/master/Chapter01/simple-counter

i only get the following - counter is not visible - how to make it visible ?

Screenshot below.

[https://i.imgur.com/n80nKvC.png](https://i.imgur.com/n80nKvC.png)

**Comment by jauyeunggithub** [comment]
> Hi Vuers - This is a beginner question so please be kind to me.
> 
> i just started learning vue using this book and i get this for the following code.
> 
> for this code - https://github.com/PacktPublishing/-Vue.js-3-By-Example/tree/master/Chapter01/simple-counter
> 
> i only get the following - counter is not visible - how to make it visible ?
> 
> Screenshot below.
> 
> https://i.imgur.com/n80nKvC.png

The first chapter doesn't use the Vue CLI to create the project.

You should include the Vue script tag as mentioned at the beginning of Chapter 1 in an HTML file. Then the rest of the code should be added below the Vue script tag in the same file.

See the example code in this repo to see the full example.
