### ISSUE TITLE
chapt3 - flower images not loading

### ISSUE THREAD

**Issue by ggb88** [PacktPublishing/-Vue.js-3-By-Example#4]
When using latest versions of all dependencies, you might run into this issue - its because of changes made to webpack fileloader, the assets need to be loaded either by 
`require(`../assets/${p.image}`).default`
or changing config file.  More information [here](https://stackoverflow.com/q/59114479/915938)

**Comment by jauyeunggithub** [comment]
> When using latest versions of all dependencies, you might run into this issue - its because of changes made to webpack fileloader, the assets need to be loaded either by
> `require(`../assets/${p.image}`).default`
> or changing config file. More information [here](https://stackoverflow.com/q/59114479/915938)

Thanks for the update
